blank_issues_enabled: false
contact_links:
  - name: Way of Working
    url: https://github.com/schedjoules/schedjoules-app/blob/main/docs/WAY_OF_WORKING_GITHUB.md
    about: Read our Way of Working before creating issues
